
#define SOIL_MOISTURE_ANALOG_READ_PIN 32

#define MULTIPLEXER_ADDRESS_A_PIN 27
#define MULTIPLEXER_ADDRESS_B_PIN 26
#define MULTIPLEXER_ADDRESS_C_PIN 25

# define SDA_PIN 21
# define SCL_PIN 22

#define LIGHT_PIN 33